### ISSUE TITLE
Мобильное меню

### ISSUE THREAD

**Issue by regina-ms** [aaccent/sovetnik_layout#10]
- Меню подуслуг не по макету
- Расстояние между адресом и режимом работы не по макету 
<details><summary>Details</summary>

![image](https://github.com/aaccent/sovetnik_layout/assets/118468038/988692ca-b895-4f80-b933-f9aaffdbd0c9)
</details>

**Comment by RamizAshurov** [comment]
- Сверстал подменю по макету
- Поправил отступы

**Comment by regina-ms** [comment]
- размер логотипа в мобильном меню не по макету
- отступ от логотипа не по макету 
- жирность шрифта у номера телеофна не по макету 
- отступ между адресом и режимом работы в макете 6px
- у ссылки Войти в личный кабинет размер шрифта в макете 16px и нижний отступ меньше 
- сломалось меню Услуги на десктопе

**Comment by RamizAshurov** [comment]
исправил размер логотипа
поправил оступы меню от логотипа
добавил жирность
поправил отступ
поправил шрифт на мобилке, нижнего отступа на мобилке нет, ссылка идет последней
Поправил подменю
