### ISSUE TITLE
Блок Шаги реализации проекта 

### ISSUE THREAD

**Issue by regina-ms** [aaccent/sovetnik_layout#12]
- Размер текста слева о заголовка не по макету 
<details><summary>Details</summary>

![image](https://github.com/aaccent/sovetnik_layout/assets/118468038/3adcbab3-066e-4beb-990e-d8e997ff8551)
</details> 

В мобильной версии :
- размер шрифта у `.section__title` и `.step__desc`не по макету 
- шрифт у `.step__title` должен быть Inter

**Comment by RamizAshurov** [comment]
- Если имеется ввиду текст справа от заголовка, то он по макету: на ширина 1600px ширина 710px
- Исправил размер шрифта у .section__title, у .step__desc все по макету: 16/22px
- Исправил
