### ISSUE TITLE
Блок Ответы на популярные вопросы 

### ISSUE THREAD

**Issue by regina-ms** [aaccent/sovetnik_layout#14]
- Межстрочный интервал и отступы от праграфов не по макету 
<details><summary>Details</summary>

![image](https://github.com/aaccent/sovetnik_layout/assets/118468038/2dbf9563-deac-416b-996c-735b36ca5b62)>
</details> 
- В мобилке шрифт у заголовков `.accordion__title` должен быть Inter

**Comment by RamizAshurov** [comment]
- Исправил
- Исправил
