### ISSUE TITLE
Страница реализованного проекта 

### ISSUE THREAD

**Issue by regina-ms** [aaccent/sovetnik_layout#16]
- `h1` не по макету 
- размер шрифта у `.list-item__title` не по макету 
<details><summary>Details</summary>

![image](https://github.com/aaccent/sovetnik_layout/assets/118468038/ed0e3fc5-4933-480a-ad80-e5d35a9b16bc)
</details> 
- Блок Описание дела не по макету - шрифт у ФИО и размеры загруженных документов

**Comment by RamizAshurov** [comment]
- Исправил. h1 в две строки
- Размер шрифта по макету: на десктопе 22/28, на мобилке 20/24
- Исправил

**Comment by foxhable** [comment]
У `.profile__name` в макете отступ снизу `8px`

**Comment by RamizAshurov** [comment]
Исправил отступ: на десктопе 8px, на мобилке - 6px
