### ISSUE TITLE
Страница Контакты 

### ISSUE THREAD

**Issue by regina-ms** [aaccent/sovetnik_layout#18]
- размер шрифта не по макету 
<details><summary>Details</summary>

![image](https://github.com/aaccent/sovetnik_layout/assets/118468038/38725200-6fdc-4dd9-bcac-1e13951c1570)
</details> 
- в мобилке скрыта карта, размер шрифтов не по макету, поехали иконки соц.сетей 
<details><summary>Details</summary>

![image](https://github.com/aaccent/sovetnik_layout/assets/118468038/bb65cc17-8a46-4584-8cc7-3fe0b9a816e4)
</details>

**Comment by RamizAshurov** [comment]
Шрифты проверил: 22/28px, по макету
Вернул карту, поправил шрифты и иконки

**Comment by foxhable** [comment]
Горизонтальный скрол появился

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/sovetnik_layout/assets/36298346/4187d6be-2474-4fbe-8260-0692284e0cce)
</details>
