### ISSUE TITLE
Отзывы

### ISSUE THREAD

**Issue by regina-ms** [aaccent/sovetnik_layout#2]
- В отзывах отсутствует кнопка Читать далее
<details><summary>Details</summary> 

![image](https://github.com/aaccent/sovetnik_layout/assets/118468038/f417eaf2-db8e-4e0a-b7cd-df187b013562)
</details> 

- В мобилке в секции Отзывы не должно быть стрелок переключения отзывов и отступа между датой и именем

**Comment by RamizAshurov** [comment]
- Кнопка "Читать далее" в отзывах есть. Она появляется, если текст занимает больше 3-ех строк
- Отступ исправил
