### ISSUE TITLE
страница Цены 

### ISSUE THREAD

**Issue by regina-ms** [aaccent/sovetnik_layout#20]
- Не меняется значение в скрытом поле `service-name`
- во всех вкладках Назавние категории кроме первой, не работает скролл при нажатии на кнопку записаться
<details><summary>Details</summary>

![image](https://github.com/aaccent/sovetnik_layout/assets/118468038/e8c279ca-adb7-4c05-8094-2536dd828c18)
</details> 
- в мобилке кнопка Записаться в макете меньше

**Comment by RamizAshurov** [comment]
у всех услуг стоит имя (service name) в  data-атрибуте 
поправил скролл
поправил размеры кнопки

**Comment by foxhable** [comment]
Высота `.prices-section__categories` не заполняет полностью контейнер как в макете
