### ISSUE TITLE
Разметка контента

### ISSUE THREAD

**Issue by foxhable** [aaccent/sovetnik_layout#21]
На страницах:
- `single-project-page.html`
- `single-service-page.html`
- `typical-page.html`

Нужно переверстать контентную часть для упрощения работы Контент Менеджерам согласно [этим правилам](https://knowledge.aaccent.ru/layout-process.html#content-text)

<details><summary>Как сверстано</summary>

```html
<div class="container">
  <div class="section__header">
    <h2 class="section__title">Кредитная статистика Центробанка</h2>
  </div>
  <div class="section__body">
    <div class="text-block">
      <p></p>
      <p></p>
    </div>
    <div class="page__inner-section inner-section">
      <h4 class="inner-section__title">Подзаголовок</h4>
      <div class="inner-section__body">
        <div class="text-block">
          <p></p>
          <p></p>
          <p></p>
        </div>
      </div>
    </div>
  </div>
</div>
```
</details>

<details><summary>Как должно быть</summary>

```html
<div class="container">
  <h2>Кредитная статистика Центробанка</h2>
  <p></p>
  <p></p>
  <h4>Подзаголовок</h4>
  <p></p>
  <p></p>
  <p></p>
</div>
```
</details> 

`.project-section__list` на странице `single-project-page.html` должно быть сделано через `table` без использования классов.

**Comment by RamizAshurov** [comment]
Исправил
