### ISSUE TITLE
Логотипы 

### ISSUE THREAD

**Issue by regina-ms** [aaccent/sovetnik_layout#3]
Лого в хедере и лого Акцент в футере меньше чем в макете (на десктопе и мобилке)

**Comment by RamizAshurov** [comment]
- Можно получить логотип компании в формате svg и без заднего фона. В футере и хедере название компании в логотипе отличаются по толщине. Так и должно быть?
- Размер логотипа Акцента исправил

**Comment by regina-ms** [comment]
В группе отправила лого в свг, его же нужо использовать в футере
