### ISSUE TITLE
Высота элементов в "Специалисты"

### ISSUE THREAD

**Issue by foxhable** [aaccent/sovetnik_layout#31]
На странице "О нас" и на главной в блоке "Специалисты". Если контент карточки станет больше, чем контент других карточек, то карточки становятся разных размеров.

<details><summary>Скрин</summary>

![image](https://github.com/aaccent/sovetnik_layout/assets/36298346/29d99b32-88ce-4725-9467-dd1ba727990d)
</details>

**Comment by regina-ms** [comment]
готово
