### ISSUE TITLE
Попап Заказать звонок

### ISSUE THREAD

**Issue by regina-ms** [aaccent/sovetnik_layout#4]
- Можно отправить форму без обязательной галочки 

- Изменяется цвет формы при повторном открытии после отправки 
<details><summary>Details</summary>

![image](https://github.com/aaccent/sovetnik_layout/assets/118468038/9cef479f-e897-4686-808d-c931ea8bfe99)
</details>

**Comment by RamizAshurov** [comment]
- Сделал галочку обязательной
- Исправил смену фона попа

**Comment by regina-ms** [comment]
теперь после отправки формы, при повторном вызове попапа нельзя выделить поля

**Comment by RamizAshurov** [comment]
Исправил
