### ISSUE TITLE
Форма на мобилке 

### ISSUE THREAD

**Issue by regina-ms** [aaccent/sovetnik_layout#5]
- Ломается верстка при добавлении файла с длинным названием 
<details><summary>Details</summary>

![image](https://github.com/aaccent/sovetnik_layout/assets/118468038/c0a02578-d213-4334-8e45-c1272aab5bc4)
</details> 

- Отступы между инпутами не по макету

**Comment by RamizAshurov** [comment]
- Поправил верстку
- Исправил отступы

**Comment by regina-ms** [comment]
у поля Комментарий `.form__input.form__input_textarea` поставь `display:block`, чтобы он заполнял свой контейнер

**Comment by RamizAshurov** [comment]
Исправил
