### ISSUE TITLE
Футер (мобилка)

### ISSUE THREAD

**Issue by regina-ms** [aaccent/sovetnik_layout#7]
- У текста после логотипа в футере межстрочный интервал не по макету
<details><summary>Details</summary>

![image](https://github.com/aaccent/sovetnik_layout/assets/118468038/3c8de76a-8fac-4a2a-a03d-559737c2a2de)
</details> 

- Нижний блок футера не по макету
<details><summary>Details</summary>

![image](https://github.com/aaccent/sovetnik_layout/assets/118468038/60049c50-0b7a-4dfc-b4f2-0b072104f6ff)
</details>

**Comment by RamizAshurov** [comment]
- Исправил интервал
- Исправил блок с логотипом

**Comment by regina-ms** [comment]
размер шрифта у текста в `.footer__bottom` сделай 14px

**Comment by RamizAshurov** [comment]
Исправил
